/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include "iostream"

unsigned long long int getNextFib(unsigned long long int a, unsigned long long int b) {

  return a+b;

}

int main() {

  unsigned long long int a = 0, b = 1, c = 0, sum = 0;

  while( c < 4000000 ) {
    c = getNextFib(a, b);
    a = b;
    b = c; 
    if( c < 4000000 && c%2 == 0) {
      sum += c;
      std::cout << c << ",";
    }
  }
  std::cout << "Sum: " << sum ;
  return 0;
}
